.PHONY: build run test migrate-up migrate-down

build:
	go build -o bin/server ./cmd/server

run:
	go run ./cmd/server

test:
	go test ./...

migrate-up:
	@echo "TODO: run migrations up"

migrate-down:
	@echo "TODO: run migrations down"
